"""empty message

Revision ID: 0835db963625
Revises: 12f12e9849d6
Create Date: 2024-05-31 11:22:43.392812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0835db963625'
down_revision = '12f12e9849d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_column('resume_file')

    # ### end Alembic commands ###
