"""empty message

Revision ID: 12f12e9849d6
Revises: dcd8ed6bb9cf
Create Date: 2024-05-30 01:29:26.367628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f12e9849d6'
down_revision = 'dcd8ed6bb9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact me', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact me', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
