"""empty message

Revision ID: 32bcf18bb107
Revises: fc82a4bab0ce
Create Date: 2024-05-29 23:14:10.526619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bcf18bb107'
down_revision = 'fc82a4bab0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')

    # ### end Alembic commands ###
