"""empty message

Revision ID: 363b007e04c3
Revises: 521918c1953d
Create Date: 2024-05-29 11:44:25.385785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363b007e04c3'
down_revision = '521918c1953d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_skill', sa.Text(), nullable=True))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('my_skill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_skill', sa.TEXT(), nullable=True))

    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_column('my_skill')

    # ### end Alembic commands ###
