"""empty message

Revision ID: 782a9037d315
Revises: a802455fead9
Create Date: 2024-05-21 13:27:18.172561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782a9037d315'
down_revision = 'a802455fead9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint('uq_users_is_admin', ['is_admin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_is_admin', type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
