"""empty message

Revision ID: ad6d12534517
Revises: f6ba8ed8c1c7
Create Date: 2024-05-24 16:45:39.678100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6d12534517'
down_revision = 'f6ba8ed8c1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('awards', sa.Integer(), nullable=True),
    sa.Column('Complete_Projects', sa.Integer(), nullable=True),
    sa.Column('Happy_Customers', sa.Integer(), nullable=True),
    sa.Column('Cups_of_coffee', sa.Integer(), nullable=True),
    sa.Column('AboutMe', sa.Text(), nullable=True),
    sa.Column('image1', sa.String(length=255), nullable=True),
    sa.Column('image2', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Happy_Customers')
        batch_op.drop_column('phone')
        batch_op.drop_column('awards')
        batch_op.drop_column('Complete_Projects')
        batch_op.drop_column('image1')
        batch_op.drop_column('job')
        batch_op.drop_column('Cups_of_coffee')
        batch_op.drop_column('image2')
        batch_op.drop_column('AboutMe')
        batch_op.drop_column('city')
        batch_op.drop_column('fullname')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('AboutMe', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Cups_of_coffee', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('job', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('image1', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Complete_Projects', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('awards', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Happy_Customers', sa.INTEGER(), nullable=True))

    op.drop_table('informations')
    # ### end Alembic commands ###
