"""empty message

Revision ID: fc82a4bab0ce
Revises: 363b007e04c3
Create Date: 2024-05-29 22:46:22.279399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc82a4bab0ce'
down_revision = '363b007e04c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
